### ISSUE TITLE
Not published

### ISSUE THREAD

**Issue by AstraLuma** [caddy-dns/rfc2136#3]
By published I mean available on https://caddyserver.com/download

**Comment by errordlien** [comment]
can we get this bumped? I would really like to use this module

**Comment by mholt** [comment]
The repo owner will need to claim it on our website (in the Account section). @KoHcoJlb let me know if you have questions about this :)

If there's no response, we can open this repo up for others to help maintain it, and they can claim it.

**Comment by KoHcoJlb** [comment]
Yeah, sure) I'll try later today

**Comment by KoHcoJlb** [comment]
Published, I believe

**Comment by mholt** [comment]
It worked! Nice job :) Thank you
