### ISSUE TITLE
Add 'rfc2136' tag to Gtihub repo project settings

### ISSUE THREAD

**Issue by pataquets** [caddy-dns/rfc2136#6]
So it's listed on [rfc2136 · GitHub Topics](https://github.com/topics/rfc2136).
Project labels are not in the settings page, but on the rightmost repo 'About' section, clicking the gear icon.

**Comment by pataquets** [comment]
@KoHcoJlb ping

**Comment by mholt** [comment]
I just went ahead and did it (easy enough) :+1:
